/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package minggu15_juvrience;

import javax.swing.JOptionPane;

/**
 * Nama : Juvrience Marcius Lim 
 * NIM : 50170035
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rbnasgor = new javax.swing.JRadioButton();
        rbmie = new javax.swing.JRadioButton();
        rbsoto = new javax.swing.JRadioButton();
        rbsop = new javax.swing.JRadioButton();
        rbnasi = new javax.swing.JRadioButton();
        TxtRBNG = new javax.swing.JTextField();
        TxtRBMG = new javax.swing.JTextField();
        TxtRBSA = new javax.swing.JTextField();
        TxtRBSK = new javax.swing.JTextField();
        TxtRBNS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtjmlNG = new javax.swing.JTextField();
        TxtjmlMG = new javax.swing.JTextField();
        TxtjmlSA = new javax.swing.JTextField();
        TxtjmlSK = new javax.swing.JTextField();
        TxtjmlNS = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TxtjmlHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("WARUNG MANTAP SEDAP");

        rbnasgor.setText("Nasi Goreng");
        rbnasgor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnasgorActionPerformed(evt);
            }
        });

        rbmie.setText("Mie Goreng");
        rbmie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmieActionPerformed(evt);
            }
        });

        rbsoto.setText("Soto Ayam");
        rbsoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsotoActionPerformed(evt);
            }
        });

        rbsop.setText("Sop Kambing");
        rbsop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsopActionPerformed(evt);
            }
        });

        rbnasi.setText("Nasi");
        rbnasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnasiActionPerformed(evt);
            }
        });

        TxtRBNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtRBNSActionPerformed(evt);
            }
        });

        jLabel2.setText("X");

        jLabel3.setText("X");

        jLabel4.setText("X");

        jLabel5.setText("X");

        jLabel6.setText("X");

        jLabel7.setText("Jumlah");

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel9.setText("Jumlah Harga");

        jLabel10.setText("Harga");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(85, 85, 85)
                .addComponent(jLabel7)
                .addGap(102, 102, 102))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbsop)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbnasgor)
                                            .addComponent(rbmie)
                                            .addComponent(rbsoto)
                                            .addComponent(rbnasi))
                                        .addGap(184, 184, 184)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtRBNS, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                            .addComponent(TxtRBSK)
                                            .addComponent(TxtRBSA, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TxtRBNG)
                                            .addComponent(TxtRBMG))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtjmlNG)
                                    .addComponent(TxtjmlMG)
                                    .addComponent(TxtjmlSA)
                                    .addComponent(TxtjmlSK)
                                    .addComponent(TxtjmlNS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(129, 129, 129)
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(TxtjmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(hitung)
                            .addGap(21, 21, 21)
                            .addComponent(hapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(exit))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbnasgor)
                            .addComponent(TxtRBNG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbmie)
                            .addComponent(TxtRBMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbsoto)
                            .addComponent(TxtRBSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbsop)
                            .addComponent(TxtRBSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbnasi)
                            .addComponent(TxtRBNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TxtjmlNG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtjmlMG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtjmlSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtjmlSK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtjmlNS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitung)
                    .addComponent(hapus)
                    .addComponent(exit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TxtjmlHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtRBNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtRBNSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtRBNSActionPerformed

    private void rbnasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnasgorActionPerformed
        int nasigoreng=15000;
        if(rbnasgor.isSelected()){
            TxtRBNG.setText(""+rbnasgor.getText());
            TxtRBNG.setText(""+nasigoreng);
        }else{
            TxtRBNG.setText("");
        }
    }//GEN-LAST:event_rbnasgorActionPerformed

    private void rbmieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmieActionPerformed
        int miegoreng=15000;
        if(rbmie.isSelected()){
            TxtRBMG.setText(""+rbmie.getText());
            TxtRBMG.setText(""+miegoreng);
        }else{
            TxtRBMG.setText("");
        }
    }//GEN-LAST:event_rbmieActionPerformed

    private void rbsotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsotoActionPerformed
        int sotoayam=15000;
        if(rbsoto.isSelected()){
            TxtRBSA.setText(""+rbsoto.getText());
            TxtRBSA.setText(""+sotoayam);
        }else{
            TxtRBSA.setText("");
        }
    }//GEN-LAST:event_rbsotoActionPerformed

    private void rbsopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsopActionPerformed
        int sopkambing=25000;
        if(rbsop.isSelected()){
            TxtRBSK.setText(""+rbsop.getText());
            TxtRBSK.setText(""+sopkambing);
        }else{
            TxtRBSK.setText("");
        }
    }//GEN-LAST:event_rbsopActionPerformed

    private void rbnasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnasiActionPerformed
        int nasi=5000;
        if(rbnasi.isSelected()){
            TxtRBNS.setText(""+rbnasi.getText());
            TxtRBNS.setText(""+nasi);
        }else{
            TxtRBNS.setText("");
        }
    }//GEN-LAST:event_rbnasiActionPerformed

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        int total=0;
        if (rbnasgor.isSelected()){
            String NG = TxtjmlNG.getText();
            int jmlNG=Integer.parseInt(NG);
            int HargaNG=jmlNG*15000;
            total=total+HargaNG;
        }
         if (rbmie.isSelected()){
            String MG = TxtjmlMG.getText();
            int jmlMG=Integer.parseInt(MG);
            int HargaMG=jmlMG*15000;
            total=total+HargaMG;
        }
          if (rbsoto.isSelected()){
            String SA = TxtjmlSA.getText();
            int jmlSA=Integer.parseInt(SA);
            int HargaSA=jmlSA*15000;
            total=total+HargaSA;
        }
           if (rbsop.isSelected()){
            String SK = TxtjmlNG.getText();
            int jmlSK=Integer.parseInt(SK);
            int HargaSK=jmlSK*25000;
            total=total+HargaSK;
        }
            if (rbnasi.isSelected()){
            String NS = TxtjmlNS.getText();
            int jmlNS=Integer.parseInt(NS);
            int HargaNS=jmlNS*5000;
            total=total+HargaNS;
        }
            TxtjmlHarga.setText("" + total);
    }//GEN-LAST:event_hitungActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        TxtjmlNG.setEditable(false);
        TxtjmlNG.setText("");
        TxtjmlMG.setEditable(false);
        TxtjmlMG.setText("");
        TxtjmlSA.setEditable(false);
        TxtjmlSA.setText("");
        TxtjmlSK.setEditable(false);
        TxtjmlSK.setText("");
        TxtjmlNS.setEditable(false);
        TxtjmlNS.setText("");
        TxtjmlHarga.setText("");
        
    }//GEN-LAST:event_hapusActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        int balas = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar ?", "Konfirmasi Keluar Aplikasi", JOptionPane.YES_NO_OPTION);
        if (balas == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtRBMG;
    private javax.swing.JTextField TxtRBNG;
    private javax.swing.JTextField TxtRBNS;
    private javax.swing.JTextField TxtRBSA;
    private javax.swing.JTextField TxtRBSK;
    private javax.swing.JTextField TxtjmlHarga;
    private javax.swing.JTextField TxtjmlMG;
    private javax.swing.JTextField TxtjmlNG;
    private javax.swing.JTextField TxtjmlNS;
    private javax.swing.JTextField TxtjmlSA;
    private javax.swing.JTextField TxtjmlSK;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbmie;
    private javax.swing.JRadioButton rbnasgor;
    private javax.swing.JRadioButton rbnasi;
    private javax.swing.JRadioButton rbsop;
    private javax.swing.JRadioButton rbsoto;
    // End of variables declaration//GEN-END:variables
}
